"""Façade for the refinement service package (M7 split).

The implementation now lives in profile_patch.py, refinement_session.py,
strategy_refinement.py, and refinement_stream.py. This module re-exports every
name that backend.app.api.routes, backend.app.services.explore, and the test
suite import so existing import paths keep working unchanged.
"""

from __future__ import annotations

import asyncio
import hashlib
import json
import logging
import re
import threading
from datetime import UTC, datetime, timedelta
from typing import Any


from backend.agents.discovery.language_support import trusted_language_options
from backend.agents.discovery.markets import normalize_market_query_tickers, resolve_tickers_from_text
from backend.agents.discovery.types import DEFAULT_EXPLORE_SOURCE_SELECTION, fold_text
from backend.agents.digestor.gmail import NewsletterCandidate, discover_newsletter_candidates
from backend.agents.librarian.text_utils import keyword_set
from backend.agents.model import ModelClient
from backend.app.core.config import get_settings
from backend.app.core.prompt_loader import load_prompt
from backend.app.db import database
from backend.app.services import explore, gmail_allowlist, model_routing

from backend.app.services.profile_patch import (
    AGENT_PENDING_FIELD,
    DEPTH_PRACTITIONER_TOKENS,
    FIELD_HINT_TEXT_SOURCE,
    FIELD_ORDER,
    GMAIL_RULES_FIELD,
    GMAIL_SENDER_SELECTION_FIELD,
    MAX_REFINEMENT_TURNS,
    MIN_REFINEMENT_TURNS,
    PENDING_STRATEGY_FIELD,
    PENDING_STRATEGY_PROFILE_KEY,
    PODCAST_STRATEGY_FIELDS,
    QUESTIONS,
    RECENCY_BREAKING_TOKENS,
    STRATEGY_REVIEW_PROFILE_KEY,
    STRATEGY_REVIEW_RESOLVED_STATUSES,
    VALID_SOURCE_ADAPTERS,
    _QUERY_YEAR_RE,
    _QUESTION_VARIANTS,
    _SOURCE_DISPLAY,
    _SOURCE_PROMPT_LABELS,
    _answered_field_for_current_question,
    _baseline_diagnostics,
    _canonicalize_must_have,
    _clean_must_have_aliases,
    _clean_requested_source_ref,
    _clean_source_queries,
    _coerce_lookback_hours,
    _coerce_profile,
    _coerce_schedule,
    _collect_hint_text,
    _contains,
    _dedupe_next_question,
    _deterministic_question,
    _diagnostics_query_snapshot,
    _email_list,
    _enrich_diagnostics,
    _ensure_source_query_coverage,
    _extract_exclusion_hints,
    _extract_json_block,
    _extract_lookback_constraint,
    _extract_lookback_hours,
    _extract_requested_sources,
    _extract_user_strategy_additions,
    _field_from_question,
    _fill_defaults,
    _first_unasked_question,
    _foreign_media_fallback_queries,
    _format_strategy_snapshot,
    _generic_requested_ref,
    _inferred_constraints,
    _is_conversational_sentence,
    _is_generic_actionable_question,
    _is_refinement_closing_language,
    _keywords,
    _lookback_amount,
    _market_tracking_interest,
    _merge_agent_profile_patch,
    _merge_foreign_language_plan,
    _merge_requested_source_hints,
    _merge_requested_source_lists,
    _merge_source_queries,
    _merge_string_lists,
    _messages,
    _models,
    _negative_answer,
    _next_missing,
    _next_priority_field,
    _normalize_depth,
    _normalize_foreign_language_plan,
    _normalize_gmail_rules,
    _normalize_question_for_repeat_check,
    _normalize_recency,
    _normalize_refinement_intent,
    _normalize_requested_sources,
    _parse_chat_payload,
    _pending_strategy_refinement,
    _pick_variant,
    _podcast_discovery_fallback_queries,
    _prune_unselected_source_fields,
    _queries_from_statement,
    _question_repeats_answered_constraint,
    _question_was_recently_asked,
    _readiness_reason,
    _recency_from_lookback_hours,
    _requested_source_was_named_by_user,
    _requested_sources_question,
    _requests_strategy_cleanup,
    _required_confirmation_field,
    _run_event_loop,
    _run_sync_complete_json,
    _run_sync_list,
    _sanitize_bounded_recency_query_years,
    _search_strategy_question,
    _seed_profile_with_hints,
    _session_response,
    _signal_strength,
    _source_selection_dict,
    _source_specific_fallback,
    _split_answer_list,
    _stable_jsonable,
    _strategy_deepening_question,
    _strategy_preview,
    _strategy_recency_label,
    _string_list,
    _trim_for_diagnostics,
    _user_authored_text,
    _visible_prose,
)

from backend.app.services.refinement_session import (
    _advance_gmail_refinement,
    _ai_gmail_discovery_plan,
    _ai_rank_gmail_candidates,
    _apply_agent_update,
    _apply_answer,
    _apply_answer_with_model,
    _apply_critique,
    _apply_freeform_refinement_answer,
    _apply_models,
    _build_refinement_agent_prompt,
    _build_refinement_prompt,
    _clean_next_question,
    _coerce_model_field_updates,
    _critique_search_plan,
    _discover_gmail_candidates,
    _extract_model_updates,
    _gmail_candidate_question,
    _gmail_refinement_question,
    _gmail_rules_from_answer,
    _initial_profile,
    _is_gmail_approval_response,
    _lookback_label,
    _privacy_markers_for_refinement,
    _refinement_model_client,
    _run_refinement_agent,
    _selected_gmail_senders,
    advance_session,
    start_session,
)

from backend.app.services.strategy_refinement import (
    _astream_strategy_fallback,
    _build_pending_strategy_refinement,
    _build_strategy_refinement_prompt,
    _pending_strategy_context,
    _pre_build_strategy_review_instruction,
    _profile_for_strategy_review,
    _proposal_was_resolved,
    _run_strategy_refinement_agent,
    _strategy_fingerprint,
    _strategy_proposal_summary,
    astream_refine_strategy,
    astream_review_strategy,
    confirm_strategy_refinement,
    refine_strategy,
    review_strategy,
)

from backend.app.services.refinement_stream import (
    _astream_fallback,
    _astream_gmail_approval,
    _astream_gmail_discovery,
    _build_refinement_chat_prompt,
    _ends_with_question,
    _ensure_foreign_language_plan,
    _ensure_reply_updates_strategy,
    _last_user_message,
    _refinement_reply_with_required_question,
    _sanitize_recent_visible_text_years,
    _strip_refinement_closing_language,
    _user_requested_strategy_snapshot,
    astream_refinement,
    expand_must_have_aliases,
)

logger = logging.getLogger(__name__)

__all__ = [
    "asyncio",
    "hashlib",
    "json",
    "logging",
    "re",
    "threading",
    "UTC",
    "datetime",
    "timedelta",
    "Any",
    "trusted_language_options",
    "normalize_market_query_tickers",
    "resolve_tickers_from_text",
    "DEFAULT_EXPLORE_SOURCE_SELECTION",
    "fold_text",
    "NewsletterCandidate",
    "discover_newsletter_candidates",
    "keyword_set",
    "ModelClient",
    "get_settings",
    "load_prompt",
    "database",
    "explore",
    "gmail_allowlist",
    "model_routing",
    "logger",
    "AGENT_PENDING_FIELD",
    "DEPTH_PRACTITIONER_TOKENS",
    "FIELD_HINT_TEXT_SOURCE",
    "FIELD_ORDER",
    "GMAIL_RULES_FIELD",
    "GMAIL_SENDER_SELECTION_FIELD",
    "MAX_REFINEMENT_TURNS",
    "MIN_REFINEMENT_TURNS",
    "PENDING_STRATEGY_FIELD",
    "PENDING_STRATEGY_PROFILE_KEY",
    "PODCAST_STRATEGY_FIELDS",
    "QUESTIONS",
    "RECENCY_BREAKING_TOKENS",
    "STRATEGY_REVIEW_PROFILE_KEY",
    "STRATEGY_REVIEW_RESOLVED_STATUSES",
    "VALID_SOURCE_ADAPTERS",
    "_QUERY_YEAR_RE",
    "_QUESTION_VARIANTS",
    "_SOURCE_DISPLAY",
    "_SOURCE_PROMPT_LABELS",
    "_advance_gmail_refinement",
    "_ai_gmail_discovery_plan",
    "_ai_rank_gmail_candidates",
    "_answered_field_for_current_question",
    "_apply_agent_update",
    "_apply_answer",
    "_apply_answer_with_model",
    "_apply_critique",
    "_apply_freeform_refinement_answer",
    "_apply_models",
    "_astream_fallback",
    "_astream_gmail_approval",
    "_astream_gmail_discovery",
    "_astream_strategy_fallback",
    "_baseline_diagnostics",
    "_build_pending_strategy_refinement",
    "_build_refinement_agent_prompt",
    "_build_refinement_chat_prompt",
    "_build_refinement_prompt",
    "_build_strategy_refinement_prompt",
    "_canonicalize_must_have",
    "_clean_must_have_aliases",
    "_clean_next_question",
    "_clean_requested_source_ref",
    "_clean_source_queries",
    "_coerce_lookback_hours",
    "_coerce_model_field_updates",
    "_coerce_profile",
    "_coerce_schedule",
    "_collect_hint_text",
    "_contains",
    "_critique_search_plan",
    "_dedupe_next_question",
    "_deterministic_question",
    "_diagnostics_query_snapshot",
    "_discover_gmail_candidates",
    "_email_list",
    "_ends_with_question",
    "_enrich_diagnostics",
    "_ensure_foreign_language_plan",
    "_ensure_reply_updates_strategy",
    "_ensure_source_query_coverage",
    "_extract_exclusion_hints",
    "_extract_json_block",
    "_extract_lookback_constraint",
    "_extract_lookback_hours",
    "_extract_model_updates",
    "_extract_requested_sources",
    "_extract_user_strategy_additions",
    "_field_from_question",
    "_fill_defaults",
    "_first_unasked_question",
    "_foreign_media_fallback_queries",
    "_format_strategy_snapshot",
    "_generic_requested_ref",
    "_gmail_candidate_question",
    "_gmail_refinement_question",
    "_gmail_rules_from_answer",
    "_inferred_constraints",
    "_initial_profile",
    "_is_conversational_sentence",
    "_is_generic_actionable_question",
    "_is_gmail_approval_response",
    "_is_refinement_closing_language",
    "_keywords",
    "_last_user_message",
    "_lookback_amount",
    "_lookback_label",
    "_market_tracking_interest",
    "_merge_agent_profile_patch",
    "_merge_foreign_language_plan",
    "_merge_requested_source_hints",
    "_merge_requested_source_lists",
    "_merge_source_queries",
    "_merge_string_lists",
    "_messages",
    "_models",
    "_negative_answer",
    "_next_missing",
    "_next_priority_field",
    "_normalize_depth",
    "_normalize_foreign_language_plan",
    "_normalize_gmail_rules",
    "_normalize_question_for_repeat_check",
    "_normalize_recency",
    "_normalize_refinement_intent",
    "_normalize_requested_sources",
    "_parse_chat_payload",
    "_pending_strategy_context",
    "_pending_strategy_refinement",
    "_pick_variant",
    "_podcast_discovery_fallback_queries",
    "_pre_build_strategy_review_instruction",
    "_privacy_markers_for_refinement",
    "_profile_for_strategy_review",
    "_proposal_was_resolved",
    "_prune_unselected_source_fields",
    "_queries_from_statement",
    "_question_repeats_answered_constraint",
    "_question_was_recently_asked",
    "_readiness_reason",
    "_recency_from_lookback_hours",
    "_refinement_model_client",
    "_refinement_reply_with_required_question",
    "_requested_source_was_named_by_user",
    "_requested_sources_question",
    "_requests_strategy_cleanup",
    "_required_confirmation_field",
    "_run_event_loop",
    "_run_refinement_agent",
    "_run_strategy_refinement_agent",
    "_run_sync_complete_json",
    "_run_sync_list",
    "_sanitize_bounded_recency_query_years",
    "_sanitize_recent_visible_text_years",
    "_search_strategy_question",
    "_seed_profile_with_hints",
    "_selected_gmail_senders",
    "_session_response",
    "_signal_strength",
    "_source_selection_dict",
    "_source_specific_fallback",
    "_split_answer_list",
    "_stable_jsonable",
    "_strategy_deepening_question",
    "_strategy_fingerprint",
    "_strategy_preview",
    "_strategy_proposal_summary",
    "_strategy_recency_label",
    "_string_list",
    "_strip_refinement_closing_language",
    "_trim_for_diagnostics",
    "_user_authored_text",
    "_user_requested_strategy_snapshot",
    "_visible_prose",
    "advance_session",
    "astream_refine_strategy",
    "astream_refinement",
    "astream_review_strategy",
    "confirm_strategy_refinement",
    "expand_must_have_aliases",
    "refine_strategy",
    "review_strategy",
    "start_session",
]
